import { IMember, Roles } from "../lib/interfaces";

export const Bf2Members: IMember[] = [
  { id: "Adri", name: "Adri", avatar: "Adri", role: Roles.Private },
  { id: "Aimless", name: "Aimless", avatar: "Aimless", role: Roles.Private },
  {
    id: "Akaorkram",
    name: "Akaorkram",
    avatar: "Akaorkram",
    role: Roles.Private,
  },
  { id: "Anaboll", name: "Anaboll", avatar: "Anaboll", role: Roles.Private },
  { id: "Aniubik", name: "Aniubik", avatar: "Aniubik", role: Roles.Private },
  { id: "Anti", name: "Anti", avatar: "Anti", role: Roles.Private },
  {
    id: "Blackf|re",
    name: "Blackf|re",
    avatar: "Blackf|re",
    role: Roles.Private,
  },
  {
    id: "Califragilistic",
    name: "Califragilistic",
    avatar: "Califragilistic",
    role: Roles.Private,
  },
  { id: "Chrunch", name: "Chrunch", avatar: "Chrunch", role: Roles.Private },
  { id: "Clawie", name: "Clawie", avatar: "Clawie", role: Roles.Private },
  { id: "Criass", name: "Criass", avatar: "Criass", role: Roles.Private },
  {
    id: "Cryptcreeper",
    name: "Cryptcreeper",
    avatar: "Cryptcreeper",
    role: Roles.Private,
  },
  { id: "Dooman", name: "Dooman", avatar: "Dooman", role: Roles.Private },
  { id: "End", name: "End", avatar: "End", role: Roles.Private },
  { id: "Energy", name: "Energy", avatar: "Energy", role: Roles.Private },
  { id: "Envy", name: "Envy", avatar: "Envy", role: Roles.Private },
  {
    id: "Flyjetandkill",
    name: "Flyjetandkill",
    avatar: "Flyjetandkill",
    role: Roles.Private,
  },
  { id: "GodbeaR", name: "GodbeaR", avatar: "GodbeaR", role: Roles.Private },
  { id: "Harsha", name: "Harsha", avatar: "Harsha", role: Roles.Private },
  { id: "Hgjw", name: "Hgjw", avatar: "Hgjw", role: Roles.Private },
  {
    id: "Irishpride",
    name: "Irishpride",
    avatar: "Irishpride",
    role: Roles.Private,
  },
  { id: "Jinky", name: "Jinky", avatar: "Jinky", role: Roles.Private },
  { id: "Kaffe", name: "Kaffe", avatar: "Kaffe", role: Roles.Private },
  { id: "Keamont", name: "Keamont", avatar: "Keamont", role: Roles.Private },
  { id: "Killer", name: "Killer", avatar: "Killer", role: Roles.Private },
  { id: "Kylling", name: "Kylling", avatar: "Kylling", role: Roles.Private },
  {
    id: "Lazyshooter",
    name: "Lazyshooter",
    avatar: "Lazyshooter",
    role: Roles.Private,
  },
  {
    id: "MaddogJr0",
    name: "MaddogJr0",
    avatar: "MaddogJr0",
    role: Roles.Private,
  },
  { id: "Mcmt", name: "Mcmt", avatar: "Mcmt", role: Roles.Private },
  { id: "Miche", name: "Miche", avatar: "Miche", role: Roles.Private },
  {
    id: "Mr.Thunderman",
    name: "Mr.Thunderman",
    avatar: "Mr.Thunderman",
    role: Roles.Private,
  },
  { id: "Mr.White", name: "Mr.White", avatar: "Mr.White", role: Roles.Private },
  { id: "Normans", name: "Normans", avatar: "Normans", role: Roles.Private },
  { id: "Nuke", name: "Nuke", avatar: "Nuke", role: Roles.Private },
  { id: "O1egon", name: "O1egon", avatar: "O1egon", role: Roles.Private },
  {
    id: "Oakleaves",
    name: "Oakleaves",
    avatar: "Oakleaves",
    role: Roles.Private,
  },
  {
    id: "Pekkaniska",
    name: "Pekkaniska",
    avatar: "Pekkaniska",
    role: Roles.Private,
  },
  { id: "Phantom", name: "Phantom", avatar: "Phantom", role: Roles.Private },
  { id: "qTah", name: "qTah", avatar: "qTah", role: Roles.Private },
  { id: "Rabbit", name: "Rabbit", avatar: "Rabbit", role: Roles.Private },
  { id: "Reiska", name: "Reiska", avatar: "Reiska", role: Roles.Private },
  {
    id: "Ribbycag3",
    name: "Ribbycag3",
    avatar: "Ribbycag3",
    role: Roles.Private,
  },
  { id: "Sarge", name: "Sarge", avatar: "Sarge", role: Roles.Private },
  {
    id: "sAviOr[gm]",
    name: "sAviOr[gm]",
    avatar: "sAviOr[gm]",
    role: Roles.Private,
  },
  { id: "SekLoa", name: "SekLoa", avatar: "SekLoa", role: Roles.Private },
  { id: "Selaron", name: "Selaron", avatar: "Selaron", role: Roles.Private },
  { id: "Serhend", name: "Serhend", avatar: "Serhend", role: Roles.Private },
  {
    id: "Sewermaster",
    name: "Sewermaster",
    avatar: "Sewermaster",
    role: Roles.Private,
  },
  { id: "ShugJr", name: "ShugJr", avatar: "ShugJr", role: Roles.Private },
  {
    id: "Spitzbueb",
    name: "Spitzbueb",
    avatar: "Spitzbueb",
    role: Roles.Private,
  },
  { id: "Star-3", name: "Star-3", avatar: "Star-3", role: Roles.Private },
  { id: "Swift", name: "Swift", avatar: "Swift", role: Roles.Private },
  { id: "Tele.b", name: "Tele.b", avatar: "Tele.b", role: Roles.Private },
  {
    id: "Tjunkfisk",
    name: "Tjunkfisk",
    avatar: "Tjunkfisk",
    role: Roles.Private,
  },
  { id: "Tokei3", name: "Tokei3", avatar: "Tokei3", role: Roles.Private },
  {
    id: "Undertaker",
    name: "Undertaker",
    avatar: "Undertaker",
    role: Roles.Private,
  },
  {
    id: "XmetallicaXguitaristX",
    name: "XmetallicaXguitaristX",
    avatar: "XmetallicaXguitaristX",
    role: Roles.Private,
  },
  {
    id: "xXDomination",
    name: "xXDomination",
    avatar: "xXDomination",
    role: Roles.Private,
  },
  {
    id: "xXSTAIRBORNEXx",
    name: "xXSTAIRBORNEXx",
    avatar: "xXSTAIRBORNEXx",
    role: Roles.Private,
  },
  { id: "Zeddius", name: "Zeddius", avatar: "Zeddius", role: Roles.Private },
  { id: "Zennappi", name: "Zennappi", avatar: "Zennappi", role: Roles.Private },
  { id: "ZeqTr", name: "ZeqTr", avatar: "ZeqTr", role: Roles.Private },
  {
    id: "zVelocity",
    name: "zVelocity",
    avatar: "zVelocity",
    role: Roles.Private,
  },
  { id: ".Zen", name: ".Zen", avatar: ".Zen", role: Roles.Private },
];

export const Bf2042Members: IMember[] = [
  { id: "JonaduDF", name: "JonaduDF", avatar: "JonaduDF", role: Roles.Private },
  {
    id: "-Sreckins-",
    name: "-Sreckins-",
    avatar: "-Sreckins-",
    role: Roles.Private,
  },
  {
    id: "iDF-Pongstroid",
    name: "iDF-Pongstroid",
    avatar: "iDF-Pongstroid",
    role: Roles.Private,
  },
  {
    id: "iDF-Naizark",
    name: "iDF-Naizark",
    avatar: "iDF-Naizark",
    role: Roles.Private,
  },
  {
    id: "iDF-Kyraga",
    name: "iDF-Kyraga",
    avatar: "iDF-Kyraga",
    role: Roles.Private,
  },
  {
    id: "Speedlund",
    name: "Speedlund",
    avatar: "Speedlund",
    role: Roles.Private,
  },
  {
    id: "iDF-Smitev",
    name: "iDF-Smitev",
    avatar: "iDF-Smitev",
    role: Roles.Private,
  },
  {
    id: "iDF-AlphabetaB",
    name: "iDF-AlphabetaB",
    avatar: "iDF-AlphabetaB",
    role: Roles.Private,
  },
  { id: "Barsjaga", name: "Barsjaga", avatar: "Barsjaga", role: Roles.Private },
  {
    id: "Air-Khaleesi",
    name: "Air-Khaleesi",
    avatar: "Air-Khaleesi",
    role: Roles.Private,
  },
  {
    id: "RED-BARON-777",
    name: "RED-BARON-777",
    avatar: "RED-BARON-777",
    role: Roles.Private,
  },
  {
    id: "Ismaele1990",
    name: "Ismaele1990",
    avatar: "Ismaele1990",
    role: Roles.Private,
  },
  {
    id: "BSG_fenrirs_j",
    name: "BSG_fenrirs_j",
    avatar: "BSG_fenrirs_j",
    role: Roles.Private,
  },
  {
    id: "II-Nelix-II",
    name: "II-Nelix-II",
    avatar: "II-Nelix-II",
    role: Roles.Private,
  },
];
